# Generated by Django 4.2.5 on 2023-12-01 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Previsoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicaoTot', models.CharField(max_length=255)),
                ('predicaoLDA', models.CharField(max_length=255)),
                ('precisaoLDA', models.FloatField()),
                ('predicaoSVC', models.CharField(max_length=255)),
                ('precisaoSVC', models.FloatField()),
                ('predicaoKNN', models.CharField(max_length=255)),
                ('precisaoKNN', models.FloatField()),
                ('predicaoRFC', models.CharField(max_length=255)),
                ('precisaoRFC', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
