# Generated by Django 4.2.5 on 2023-10-19 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicativo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalhesknn',
            old_name='precisao',
            new_name='precisaoKNN',
        ),
        migrations.RenameField(
            model_name='detalhesknn',
            old_name='predicao',
            new_name='predicaoKNN',
        ),
        migrations.RenameField(
            model_name='detalheslda',
            old_name='precisao',
            new_name='precisaoLDA',
        ),
        migrations.RenameField(
            model_name='detalheslda',
            old_name='predicao',
            new_name='predicaoLDA',
        ),
        migrations.RenameField(
            model_name='detalhesrfc',
            old_name='precisao',
            new_name='precisaoRFC',
        ),
        migrations.RenameField(
            model_name='detalhesrfc',
            old_name='predicao',
            new_name='predicaoRFC',
        ),
        migrations.RenameField(
            model_name='detalhessvc',
            old_name='precisao',
            new_name='precisaoSVC',
        ),
        migrations.RenameField(
            model_name='detalhessvc',
            old_name='predicao',
            new_name='predicaoSVC',
        ),
        migrations.RenameField(
            model_name='previsoes',
            old_name='previsao',
            new_name='predicaoTot',
        ),
    ]
